name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22.9.0]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Check if pnpm is installed
        run: pnpm -v
      
      - name: Use Node.js 22.9.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install

      - name: Test index.ts file
        id: test-action
        uses: ./
    
      - name: Stop Apache service
        run: sudo service apache2 stop

      - name: Disable Apache service
        run: sudo update-rc.d apache2 disable

      - name: Build Docker image
        run: docker build -t my-caddy-server .

      - name: Run Docker container
        run: |
          docker run -d --name caddy-server -p 80:80 -p 443:443 my-caddy-server

      - name: Test Caddy server
        run: |
          sleep 5  
          curl --fail http://127.0.0.1/ || exit 1

      - name: Stop and remove Docker container
        run: docker stop caddy-server && docker rm caddy-server
