name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          cache: npm

      - name: Install Dependencies
        id: install-dependencies
        run: npm ci

      - name: Check Format
        id: check-format
        run: npm run format:check

      - name: Lint
        id: lint
        run: npm run lint

      - name: Test
        id: test
        run: npm run test

      - name: Build
        id: build
        run: npm run build

  test-action:
    name: Github Action Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 2000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"