name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js 22.9.0
      uses: actions/setup-node@v2
      with:
        node-version: 22.9.0 # Specify your Node.js version
        cache: 'pnpm' # Enable caching for pnpm

    - name: Install pnpm
      run: npm install -g pnpm # Install pnpm globally

    - name: Check pnpm version
      run: pnpm -v  # This will output the version of pnpm installed

    - name: Install dependencies & build
      run: pnpm install && pnpm build

    - name: Build Docker image
      run: docker build -t my-caddy-server .

    - name: Run Docker container
      run: |
        docker run -d --name caddy-server -p 80:80 -p 443:443 my-caddy-server
        # Add any additional commands to verify that the server is running, if necessary
    - name: Test Caddy server
      run: |
          sleep 5  # Wait for a few seconds to ensure the server starts up
          curl --fail http://localhost || exit 1

    - name: Stop and remove Docker container
      run: docker stop caddy-server && docker rm caddy-server
  # test-action:
  #   name: Github Action Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Test Local Action
  #       id: test-action
  #       uses: ./
  #       with:
  #         milliseconds: 2000

  #     - name: Print Output
  #       id: output
  #       run: echo "${{ steps.test-action.outputs.time }}"
